Debian packaging / init.d scripts updated to work with disco.py

diff --git a/debian/disco-node.init b/debian/disco-node.init
--- a/debian/disco-node.init
+++ b/debian/disco-node.init
@@ -17,62 +17,103 @@ NAME=disco-node
 DESC="web server for disco"
 SCRIPTNAME=/etc/init.d/$NAME
 
-DAEMON_OPTS="-f /etc/disco/lighttpd.conf"
-
 test -x $DAEMON || exit 0
 
 set -e -a
-. /etc/disco/disco.conf
 
-PIDFILE="$DISCO_PID_DIR/disco-lighttpd.pid"
+#PIDFILE="$DISCO_PID_DIR/disco-lighttpd.pid"
 
 . /lib/lsb/init-functions
 
+DAEMONUSER=disco   # Users to run the daemons as. If this value
+                   # is set start-stop-daemon will chuid the server
+
+# Check that the user exists (if we set a user)
+# Does the user exist?
+if [ -n "$DAEMONUSER" ] ; then
+    if getent passwd | grep -q "^$DAEMONUSER:"; then
+        # Obtain the uid and gid
+        DAEMONUID=`getent passwd |grep "^$DAEMONUSER:" | awk -F : '{print $3}'`
+        DAEMONGID=`getent passwd |grep "^$DAEMONUSER:" | awk -F : '{print $4}'`
+    else
+        log_failure_msg "The user $DAEMONUSER, required to run $NAME does not exist."
+        exit 1
+    fi
+fi
+
+running() {
+    [ -z "$(disco worker status | grep stopped)" ]
+    errcode=$?
+    return $errcode
+}
+
+start_server() {
+        disco worker start 
+        errcode=$?
+	return $errcode
+}
+
+stop_server() {
+        disco worker stop
+        errcode=$?
+	return $errcode
+}
+
 case "$1" in
-    start)
-        log_daemon_msg "Starting $DESC" $NAME
-        if ! start-stop-daemon --start --quiet --oknodo \
-            --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
-        then
-            log_end_msg 1
-        else
+  start)
+	log_daemon_msg "Starting $DESC " "$NAME"
+        # Check if it's running first
+        if running ;  then
+            log_progress_msg "apparently already running"
             log_end_msg 0
+            exit 0
         fi
-        ;;
-    stop)
-        log_daemon_msg "Stopping $DESC" $NAME
-        if start-stop-daemon --quiet --stop --oknodo --retry 30 --oknodo \
-            --pidfile $PIDFILE --exec $DAEMON
-        then
-            rm -f $PIDFILE
-            log_end_msg 0
-        else
-            log_end_msg 1
-        fi
-        ;;
-    reload)
-        log_daemon_msg "Reloading $DESC configuration" $NAME
-        if start-stop-daemon --stop --signal 2 --oknodo --retry 30 --oknodo \
-            --quiet --pidfile $PIDFILE --exec $DAEMON
-        then
-            if start-stop-daemon --start --quiet  \
-                --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS ; then
+        if start_server ; then
+            # NOTE: Some servers might die some time after they start,
+            # this code will detect this issue if STARTTIME is set
+            # to a reasonable value
+            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
+            if  running ;  then
+                # It's ok, the server started and is running
                 log_end_msg 0
             else
+                # It is not running after we did start
                 log_end_msg 1
             fi
         else
+            # Either we could not start it
             log_end_msg 1
         fi
+	;;
+  stop)
+        log_daemon_msg "Stopping $DESC" "$NAME"
+        stop_server || errcode=$?
+        log_end_msg $errcode
         ;;
-    restart|force-reload)
-        $0 stop
-        test -r  $PIDFILE && while pidof lighttpd | \
-            grep -q `cat $PIDFILE 2>/dev/null` 2>/dev/null ; do sleep 1; done
-        $0 start
+    restart)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+		errcode=0
+        stop_server || errcode=$?
+        # Wait some sensible amount, some server need this
+        [ -n "$DIETIME" ] && sleep $DIETIME
+        start_server || errcode=$?
+        [ -n "$STARTTIME" ] && sleep $STARTTIME
+        running || errcode=$?
+        log_end_msg $errcode
+	;;
+    status)
+        log_daemon_msg "Checking status of $DESC" "$NAME"
+        if running ;  then
+            log_progress_msg "running"
+            log_end_msg 0
+        else
+            log_progress_msg "apparently not running"
+            log_end_msg 1
+            exit 1
+        fi
         ;;
     *)
-        echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+        echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
         exit 1
         ;;
 esac
